apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - spark-events-pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
commonLabels:
  app.kubernetes.io/component: history
  app.kubernetes.io/instance: spark
  app.kubernetes.io/managed-by: kubectl
  app.kubernetes.io/name: spark
images:
  - name: spark
    newName: apache/spark
    newTag: 3.5.2
